name: Bit Init
on:
  pull_request:
    types:
      - opened
      - synchronize  
jobs:
    start:
      uses: ./.github/workflows/bit-init.yml  
      secrets:
        BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}



