name: Bit Init
on:
  pull_request:
    types:
      - opened
      - synchronize  
jobs:
    start:
      uses: Flinten/bit-poc.git/.github/workflows/bit-init.yml@tag-export  
      secrets:
        BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}



