name: Bit Init
on:
  pull_request:
    types:
      - opened
      - synchronize  
jobs:
    Bit-init:
      uses: ./.github/workflows/bit-init.yml  
      secrets:
        BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}
    Bit-verify:
      needs: Bit-init  
      uses: ./.github/workflows/verify.yml  
      secrets:
        BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}        



