name: test workflow
on:
  pull_request:
    types:
      - opened
  push:    
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize Bit
        uses: bit-tasks/init@v1
      - name: Bit Verify
        uses: bit-tasks/verify@v1
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch          
#      - name: create lane
#        run: |
#          bit lane create test-casper --scope flinten.privat-poc
#          bit lane show
#          bit lane rename ${{ steps.extract_branch.outputs.branch }}
#          bit export  
      - name: Bit Pull Request
        uses: bit-tasks/pull-request@v1   
